# Generated by Django 4.2.5 on 2024-08-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_created_at_alter_feedback_created_at_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='feedback',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True),
        # ),
        # migrations.AlterField(
        #     model_name='reservation',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True),
        # ),
        migrations.AddField(
            model_name='reservation',
            name='token',
            field=models.CharField(max_length=10, unique=True, default='DEFAULT1234'),
        ),
    ]
